apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: huma-app

build:
  artifacts:
    - image: huma
      docker:
        dockerfile: Dockerfile

test:
  - image: huma
    custom:
      - command: go test --cover ./...
        timeoutSeconds: 600

deploy:
  helm:
    releases:
      - name: cnpg-operator
        remoteChart: cloudnative-pg
        repo: https://cloudnative-pg.github.io/charts
        namespace: cnpg-system
        createNamespace: true
        wait: true

      - name: atlas-operator
        remoteChart: oci://ghcr.io/ariga/charts/atlas-operator
        namespace: atlas-operator
        createNamespace: true
        wait: true
        setValueTemplates:
          prewarmDevDB: false

      - name: db
        chartPath: ./helm/postgres
        namespace: "{{.NAMESPACE}}"
        createNamespace: true
        wait: true
        setValueTemplates:
          cluster.instances: "{{.HUMA_DB_INSTANCES}}"
          cluster.image.version: "{{.HUMA_DB_IMAGE_VERSION}}"
          cluster.storage.size: "{{.HUMA_DB_STORAGE_SIZE}}"
          cluster.database.name: "{{.HUMA_DB_DATABASE_NAME}}"
          cluster.database.user: "{{.HUMA_DB_DATABASE_USER}}"
          cluster.database.secretName: "{{.HUMA_DB_DATABASE_PASSWORD_SECRET_NAME}}"
          cluster.database.password: "{{.HUMA_DB_DATABASE_PASSWORD}}"

      - name: db-migrate
        chartPath: ./helm/migrate
        namespace: "{{.NAMESPACE}}"
        createNamespace: true
        wait: true
        setValueTemplates:
          secret.store.postgresRwUri: "{{.HUMA_DB_RW_DATABASE_URL}}"

      - name: nats
        remoteChart: nats
        repo: https://nats-io.github.io/k8s/helm/charts/
        namespace: "{{.NAMESPACE}}"
        createNamespace: true
        wait: true
        setValueTemplates:
          config.jetstream.enabled: "{{.HUMA_NATS_JETSTREAM_ENABLED}}"
          config.jetstream.fileStore.enabled: "{{.HUMA_NATS_JETSTREAM_FILESTORE_ENABLED}}"
          config.jetstream.fileStore.pvc.enabled: "{{.HUMA_NATS_JETSTREAM_PVC_ENABLED}}"
          config.jetstream.fileStore.pvc.size: "{{.HUMA_NATS_JETSTREAM_STORAGE_SIZE}}"

      - name: api
        chartPath: ./helm/huma
        namespace: "{{.NAMESPACE}}"
        createNamespace: true
        skipBuildDependencies: true
        setValueTemplates:
          deployment.replicas: "{{.API_DEPLOYMENT_REPLICAS}}"
          deployment.image.repository: "{{.IMAGE_REPO_huma}}"
          deployment.image.tag: "{{.IMAGE_TAG_huma}}@{{.IMAGE_DIGEST_huma}}"
          deployment.args[0]: "{{.API_DEPLOYMENT_ARG}}"
          deployment.container.name: "{{.API_DEPLOYMENT_CONTAINER_NAME}}"
          deployment.container.port: "{{.API_DEPLOYMENT_CONTAINER_PORT}}"
          service.port: "{{.API_SERVICE_PORT}}"
          secret.store.postgresRwUri: "{{.HUMA_DB_RW_DATABASE_URL}}"
          secret.store.postgresRoUri: "{{.HUMA_DB_RO_DATABASE_URL}}"
          secret.store.postgresRUri: "{{.HUMA_DB_R_DATABASE_URL}}"