apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  config.alloy: |
    discovery.kubernetes "pods" {
      role = "pod"

      namespaces {
        names = [{{ .Values.namespace | quote }}]
      }
    }

    loki.source.kubernetes "pods" {
      targets    = discovery.kubernetes.pods.targets
      forward_to = [loki.process.pods.receiver]
    }

    loki.process "pods" {
      stage.cri {}

      stage.json {
        expressions = {
          msg        = "msg",
          level      = "level",
          request_id = "request_id",
        }
      }

      stage.labels {
        values = {
          level      = "level",
          request_id = "request_id",
        }
      }

      forward_to = [loki.write.default.receiver]
    }

    loki.write "default" {
      endpoint {
        url = {{ .Values.lokiPushURL | quote }}
      }
    }
