apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cluster.database.secretName }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.cluster.database.user }}
  password: {{ .Values.cluster.database.password }}