apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.deployment.container.name }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          args: {{ toYaml .Values.deployment.args | nindent 12 }}
          ports:
            - containerPort: {{ .Values.deployment.container.port }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.deployment.container.port }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.deployment.container.port }}
          env:
            - name: API_SERVICE_PORT
              value: {{ .Values.service.port | quote }}
            - name: API_SERVICE_POSTGRES_RW_URI
              value: {{ .Values.secret.store.postgresRwUri | quote }}
            - name: API_SERVICE_POSTGRES_RO_URI
              value: {{ .Values.secret.store.postgresRoUri | quote }}
            - name: API_SERVICE_POSTGRES_R_URI
              value: {{ .Values.secret.store.postgresRUri | quote }}