apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
type: Opaque
data:
  database.mongoUri: {{ .Values.secret.database.mongoUri | b64enc | quote }}