apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
type: Opaque
data:
  store.postgresRwUri: {{ .Values.secret.store.postgresRwUri | b64enc | quote }}
  store.postgresRoUri: {{ .Values.secret.store.postgresRoUri | b64enc | quote }}
  store.postgresRUri: {{ .Values.secret.store.postgresRUri | b64enc | quote }}
  nats.Uri: {{ .Values.secret.nats.uri | b64enc | quote }}