deployment:
  replicas: 1
  image:
    repository: huma
    tag: latest
    pullPolicy: IfNotPresent
  args: [""]
  container:
    port: 8000

service:
  type: LoadBalancer
  port: 8000
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8000"

secret:
  store:
    postgresRwUri: ""
    postgresRoUri: ""
    postgresRUri: ""