deployment:
  replicas: 1
  image:
    repository: huma
    tag: latest
    pullPolicy: IfNotPresent
  args: [""]
  container:
    port: 8000

workflow:
  workerCount: 4

service:
  type: LoadBalancer
  port: 8000

secret:
  store:
    postgresRwUri: ""
    postgresRoUri: ""
    postgresRUri: ""
  nats:
    uri: ""
  jwtSecret: ""