apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  urlFrom:
    secretKeyRef:
      name: {{ .Release.Name }}
      key: url
  schema:
    sql: |
{{- range $path, $_ := .Files.Glob "schemas/*.sql" }}
{{ $.Files.Get $path | nindent 6 }}
{{- end }}
