apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
type: Opaque
stringData:
  url: {{ .Values.secret.store.postgresRwUri | quote }}
