datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        isDefault: true
        url: http://prometheus-server.huma.svc.cluster.local
      - name: Loki
        type: loki
        access: proxy
        isDefault: false
        url: http://loki-gateway.huma.svc.cluster.local
